; appname=FamilyTree
; backend=servlet
; sessiontimeout=120
; smtphost=smtp.gmail.com
; smtpport=465
; smtpuser=
; smtppass=
; tomcatpath=/opt/tomcat
; httpport=8080
; httpsport=8443
; db=h2
; dbfile=./FamilyTree.db
; dbmode=update
; indexdir=searchindex
; pluginbuildpollserver=true
; pluginbuildpollwaittime=10000
; pluginbuildpollnumberoftries=3
; pluginbuildrestartserver=false
backend=servlet
tomcatpath=/dev/null
appname=FamilyTree
; db=h2mem
; dbfile=./FamilyTree.db
; dbmode=create-drop

dbserver=localhost
dbuser=mysql
dbpassword=password
dbname=webdsldb
dbmode=update

indexdir=/searchindex

httpport=8080
httpsport=8443